/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/galactic-incident-397b266af9604b9fbf0a4e5446cf864b
title: Galactic Incident
*/
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      animation_0: mixer.clipAction(animations[0], group.current),
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_0.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_1.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_2.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_3.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_4.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_5.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_6.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_7.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_8.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_9.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_10.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_11.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_12.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_13.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_14.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_15.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_16.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_17.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_18.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_19.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_20.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_21.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_22.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_23.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_24.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_25.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_26.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_27.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_28.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_29.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_30.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_31.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_32.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_33.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_34.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_35.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_36.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_37.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_38.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_39.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_40.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_41.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_42.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_43.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_44.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_45.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_46.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_47.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_48.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_49.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_50.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_51.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_52.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_53.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_54.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_55.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_56.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_57.geometry} />
        </group>
        <group scale={[0, 0, 0]}>
          <points material={materials['Scene_-_Root']} geometry={nodes.mesh_58.geometry} />
        </group>
        <points material={materials['Scene_-_Root']} geometry={nodes.mesh_59.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
